package com.demo.file.domain;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_file
 *
 * @mbg.generated do_not_delete_during_merge Wed Dec 13 16:38:01 CST 2017
 */
public class SysFile {
    /**
     * Database Column Remarks:
     * 文件主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.id
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private String id;

    /**
     * Database Column Remarks:
     * 文件路径
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.path
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private String path;

    /**
     * Database Column Remarks:
     * 文件类型
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.type
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private String type;

    /**
     * Database Column Remarks:
     * 文件大小
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.size
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private Long size;

    /**
     * Database Column Remarks:
     * 文件名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.name
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private String name;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_time
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 创建人主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.creator
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private String creator;

    /**
     * Database Column Remarks:
     * 文件状态（0：删除，1启用，2禁用）
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.status
     *
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.id
     *
     * @return the value of sys_file.id
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.id
     *
     * @param id the value for sys_file.id
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.path
     *
     * @return the value of sys_file.path
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.path
     *
     * @param path the value for sys_file.path
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.type
     *
     * @return the value of sys_file.type
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.type
     *
     * @param type the value for sys_file.type
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.size
     *
     * @return the value of sys_file.size
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.size
     *
     * @param size the value for sys_file.size
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.name
     *
     * @return the value of sys_file.name
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.name
     *
     * @param name the value for sys_file.name
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_time
     *
     * @return the value of sys_file.create_time
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_time
     *
     * @param createTime the value for sys_file.create_time
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.creator
     *
     * @return the value of sys_file.creator
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.creator
     *
     * @param creator the value for sys_file.creator
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.status
     *
     * @return the value of sys_file.status
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.status
     *
     * @param status the value for sys_file.status
     * @mbg.generated Wed Dec 13 16:38:01 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}